import type { Metadata } from "next";
import "@/styles/globals.css";
import { fontSans } from "@/config/fonts";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn(fontSans.variable, "antialiased")}>{children}</body>
    </html>
  );
}
